# Generated by Django 5.2.11 on 2026-02-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryterm",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="التصنيف"
            ),
        ),
    ]
